version: '3'

services:
  my-pets-api:
    container_name: my-pets-api
    build:
      context: .
      dockerfile: ./apps/my-pets-api/Dockerfile
    restart: always
    ports:
      - 4444:4444
    networks:
      - app_network
  my-pets-web:
    container_name: my-pets-web
    build:
      context: .
      dockerfile: ./apps/my-pets-web/Dockerfile
    restart: always
    ports:
      - 5222:5222
    networks:
      - app_network

volumes:
  data:

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: false
