query getListOfPets {
	getListOfPets {
		_id
		petName
		petType
		petAllergens
		ownerPhoneNumber
		petTreating
		userId
		petDescriptionCustomFieldIds
		petGender
		petDescriptionCustomFields {
			title
			text
		}
		petPicture
		_permissions
		_databaseId
		_collectionId
		_updatedAt
		_createdAt
		petAddressId
		petAddress {
			petAddress
			petAddressCoords
		}
	}
}
