query getPet($petId: String!) {
	getPet(petId: $petId) {
		_createdAt
		_updatedAt
		_collectionId
		_id
		_permissions
		_databaseId

		userId
		petName
		petType
		petAllergens
		ownerPhoneNumber
		petTreating
		petPicture
		petDescriptionCustomFieldIds
		petGender
		petDescriptionCustomFields {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			title
			text
		}
		petAddressId
		petAddress {
			petAddress
			petAddressCoords
		}
		lostPetLocations {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			coords
		}
	}
}
