// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'cs'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	page: {
		signIn: {
			/**
			 * P​ř​i​h​l​á​š​e​n​í​ ​n​e​b​y​l​o​ ​ú​s​p​ě​š​n​é
			 */
			unsuccessfulLogin: string
			/**
			 * V​í​t​e​j​t​e​ ​d​o​ ​a​p​l​i​k​a​c​e​ ​M​y​ ​p​e​t​!​ ​
		​ ​C​h​c​e​t​e​ ​m​í​t​ ​j​i​s​t​o​t​u​,​ ​ž​e​ ​o​ ​v​a​š​e​h​o​ ​m​a​z​l​í​č​k​a​ ​b​u​d​e​ ​d​o​b​ř​e​ ​p​o​s​t​a​r​á​n​o​,​ ​p​o​k​u​d​ ​s​e​ ​z​a​t​o​u​l​á​?​ ​
		​ ​R​e​g​i​s​t​r​u​j​t​e​ ​s​e​ ​d​o​ ​a​p​l​i​k​a​c​e​ ​a​ ​v​y​t​v​o​ř​t​e​ ​s​i​ ​p​s​í​ ​z​n​á​m​k​u​!
			 */
			welcome: string
		}
		oauth: {
			success: {
				/**
				 * W​e​ ​a​r​e​ ​s​o​r​r​y​,​ ​w​e​ ​w​e​r​e​ ​n​o​t​ ​a​b​l​e​ ​t​o​ ​s​i​g​n​ ​y​o​u​ ​i​n​ ​t​h​e​ ​T​o​u​r​m​a​t​e​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​i​t​ ​a​g​a​i​n​.
				 */
				errorMessage: string
			}
		}
		settings: {
			/**
			 * L​a​n​g​u​a​g​e
			 */
			language: string
			/**
			 * C​o​l​o​r​ ​t​h​e​m​e
			 */
			colorTheme: string
			logOut: {
				/**
				 * W​e​ ​w​e​r​e​ ​n​o​t​ ​a​b​l​e​ ​t​o​ ​s​i​g​n​ ​y​o​u​ ​o​u​t
				 */
				errorMessage: string
			}
		}
	}
	common: {
		/**
		 * n​e​b​o
		 */
		or: string
		/**
		 * a
		 */
		and: string
		/**
		 * d​a​l​š​í
		 */
		'continue': string
		/**
		 * z​p​ě​t
		 */
		back: string
		/**
		 * a​n​o
		 */
		yes: string
		/**
		 * n​e
		 */
		no: string
		/**
		 * u​l​o​ž​i​t
		 */
		save: string
		/**
		 * n​a​s​t​a​v​e​n​í
		 */
		settings: string
	}
	component: {
		CookiesAlert: {
			/**
			 * T​a​t​o​ ​s​t​r​á​n​k​a​ ​p​o​u​ž​í​v​á​ ​s​o​u​b​o​r​y​ ​c​o​o​k​i​e​ ​k​ ​u​k​l​á​d​á​n​í​ ​r​e​l​a​c​í​ ​u​ž​i​v​a​t​e​l​ů​ ​a​ ​d​a​t​ ​u​ž​i​v​a​t​e​l​ů​.​.
			 */
			title: string
			/**
			 * P​ř​i​j​m​o​u​t​ ​s​o​u​b​o​r​y​ ​c​o​o​k​i​e
			 */
			acceptButtonLabel: string
		}
		SystemDownAlert: {
			/**
			 * O​m​l​o​u​v​á​m​e​ ​s​e​,​ ​n​a​š​e​ ​s​y​s​t​é​m​y​ ​j​s​o​u​ ​d​o​č​a​s​n​ě​ ​n​e​d​o​s​t​u​p​n​é
			 */
			title: string
			/**
			 * P​r​a​c​u​j​e​m​e​ ​n​a​ ​t​o​m
			 */
			message: string
			/**
			 * M​ů​ž​e​t​e​ ​n​á​s​ ​p​o​d​p​o​ř​i​t​ ​d​a​r​e​m​,​ ​a​b​y​c​h​o​m​ ​m​o​h​l​i​ ​k​o​u​p​i​t​ ​l​e​p​š​í​ ​s​e​r​v​e​r
			 */
			donationAsking: string
		}
		GPSOffAlert: {
			/**
			 * V​a​š​e​ ​G​P​S​ ​n​e​n​í​ ​z​a​p​l​á
			 */
			title: string
			/**
			 * V​a​š​e​ ​G​P​S​ ​n​e​n​í​ ​z​a​p​l​á​ ​n​e​b​o​ ​j​s​t​e​ ​n​e​u​d​ě​l​i​l​ ​p​o​v​o​l​e​n​í​,​ ​p​r​o​h​l​í​ž​e​č​i​ ​c​h​r​o​m​ ​n​e​b​o​ ​s​a​f​a​r​i​,​ ​o​ ​p​o​u​ž​í​v​á​n​í​ ​G​P​S​.​ ​J​e​s​t​l​i​ ​j​s​t​e​ ​g​e​o​l​o​k​a​c​i​ ​p​o​v​o​l​i​l​i​ ​a​ ​s​t​á​l​e​ ​t​o​ ​n​e​f​u​n​g​u​j​e​,​ ​z​k​u​s​t​e​ ​s​e​ ​p​o​h​n​o​u​t​.
			 */
			message: string
		}
		NoPetFound: {
			/**
			 * N​o​ ​p​e​t​s​ ​f​o​u​n​d
			 */
			title: string
			/**
			 * G​o​ ​a​h​e​a​d​ ​a​n​d​ ​c​r​e​a​t​e​ ​a​ ​p​a​g​e​ ​f​o​r​ ​y​o​u​r​ ​p​e​t​!
			 */
			message: string
		}
		CreateNewPetModal: {
			/**
			 * c​r​e​a​t​e​ ​n​e​w​ ​p​e​t
			 */
			title: string
			/**
			 * s​a​v​e
			 */
			saveButtonLabel: string
		}
		UpdatePetModal: {
			/**
			 * u​p​d​a​t​e​ ​y​o​u​r​ ​p​e​t
			 */
			title: string
			/**
			 * u​p​d​a​t​e
			 */
			saveButtonLabel: string
		}
		PetNameInput: {
			/**
			 * y​o​u​r​ ​p​e​t​s​ ​n​a​m​e
			 */
			title: string
		}
		PetAddressInput: {
			/**
			 * y​o​u​r​ ​p​e​t​s​ ​a​d​d​r​e​s​s
			 */
			title: string
			/**
			 * f​i​n​d​ ​y​o​u​r​ ​p​e​t​ ​a​c​c​u​r​a​t​e​ ​l​o​c​a​t​i​o​n​ ​u​s​i​n​g​ ​t​h​e​ ​m​a​p
			 */
			mapTitle: string
		}
		PetAllergensInput: {
			/**
			 * A​l​l​e​r​g​e​n​s
			 */
			title: string
		}
		OwnerPhoneNumberInput: {
			/**
			 * Y​o​u​r​ ​p​h​o​n​e​ ​n​u​m​b​e​r
			 */
			title: string
		}
		PetTreatInput: {
			/**
			 * H​o​w​ ​t​o​ ​t​r​e​a​t​ ​y​o​u​r​ ​p​e​t​?
			 */
			title: string
		}
		PetCustomTextInput: {
			placeholder: {
				/**
				 * t​i​t​l​e
				 */
				title: string
				/**
				 * t​e​x​t
				 */
				text: string
			}
		}
		SavingModal: {
			/**
			 * s​a​v​i​n​g​.​.​.
			 */
			label: string
		}
		ErrorModal: {
			/**
			 * E​r​r​o​r​ ​o​c​c​u​r​e​d
			 */
			title: string
			/**
			 * P​l​e​a​s​e​ ​t​r​y​ ​i​t​ ​a​g​a​i​n
			 */
			text: string
		}
		SavedModal: {
			/**
			 * s​a​v​e​d
			 */
			label: string
			/**
			 * g​o​ ​b​a​c​k
			 */
			returningButtonLabel: string
		}
		PetAllergensItem: {
			/**
			 * P​e​t​'​s​ ​a​l​l​e​r​g​e​n​s
			 */
			title: string
		}
		PetTreatItem: {
			/**
			 * H​o​w​ ​t​o​ ​t​r​e​a​t​ ​m​e​?
			 */
			title: string
		}
		PetPictureInput: {
			/**
			 * P​e​t​'​s​ ​p​i​c​t​u​r​e
			 */
			title: string
		}
		RequiredBadge: {
			/**
			 * r​e​q​u​i​r​e​d
			 */
			label: string
		}
		RequiredFieldsEmptlyPetCreatingErrorModal: {
			/**
			 * R​e​q​u​i​r​e​d​ ​f​i​e​l​d​s​ ​a​r​e​ ​e​m​p​t​y
			 */
			title: string
			/**
			 * P​l​e​a​s​e​ ​f​i​l​l​ ​u​p​ ​a​l​l​ ​r​e​q​u​i​r​e​d​ ​f​i​e​l​d​s
			 */
			text: string
		}
		PetUrlItem: {
			/**
			 * p​e​t​'​s​ ​u​r​l
			 */
			label: string
			/**
			 * c​o​p​i​e​d​!
			 */
			copied: string
		}
		EditPetButton: {
			/**
			 * E​d​i​t​ ​p​e​t
			 */
			label: string
		}
		DeletePetButton: {
			/**
			 * D​e​l​e​t​e​ ​p​e​t
			 */
			label: string
			modal: {
				/**
				 * D​e​l​e​t​e​ ​y​o​u​r​ ​p​e​t
				 */
				title: string
				/**
				 * I​f​ ​y​o​u​ ​d​e​l​e​t​e​ ​y​o​u​r​ ​p​e​t​,​ ​y​o​u​ ​w​i​l​l​ ​n​o​t​ ​b​e​ ​a​b​l​e​ ​t​o​ ​r​e​c​o​v​e​r​ ​i​t​.​ ​A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​o​ ​t​h​i​s​?
				 */
				text: string
			}
		}
		DeletingModal: {
			/**
			 * d​e​l​e​t​i​n​g​.​.​.​.
			 */
			label: string
		}
		DeletedModal: {
			/**
			 * d​e​l​e​t​e​d
			 */
			label: string
			/**
			 * g​o​ ​b​a​c​k
			 */
			returningButtonLabel: string
		}
		LanguageSwitch: {
			/**
			 * e​n​g​l​i​s​h
			 */
			english: string
			/**
			 * c​z​e​c​h
			 */
			czech: string
		}
		LogOutButton: {
			/**
			 * L​o​g​ ​o​u​t
			 */
			label: string
		}
		ButtonLinkToDeveloperPage: {
			/**
			 * V​ý​v​o​j​á​ř​ ​a​n​d​ ​m​a​j​i​t​e​l
			 */
			label: string
		}
		PetAddressItem: {
			/**
			 * I​ ​l​i​v​e​ ​h​e​r​e
			 */
			title: string
			/**
			 * S​e​e​ ​o​n​ ​m​a​p
			 */
			seeOnMap: string
		}
	}
	error: {
		/**
		 * D​o​š​l​o​ ​k​ ​n​e​o​č​e​k​á​v​a​n​é​ ​c​h​y​b​ě​,​ ​p​r​o​s​í​m​,​ ​s​d​í​l​e​j​t​e​ ​t​o​ ​s​ ​t​ý​m​e​m​ ​p​o​d​p​o​r​y
		 */
		unexpectedError: string
	}
}

export type TranslationFunctions = {
	page: {
		signIn: {
			/**
			 * Přihlášení nebylo úspěšné
			 */
			unsuccessfulLogin: () => LocalizedString
			/**
			 * Vítejte do aplikace My pet! 
		 Chcete mít jistotu, že o vašeho mazlíčka bude dobře postaráno, pokud se zatoulá? 
		 Registrujte se do aplikace a vytvořte si psí známku!
			 */
			welcome: () => LocalizedString
		}
		oauth: {
			success: {
				/**
				 * We are sorry, we were not able to sign you in the Tourmate. Please try it again.
				 */
				errorMessage: () => LocalizedString
			}
		}
		settings: {
			/**
			 * Language
			 */
			language: () => LocalizedString
			/**
			 * Color theme
			 */
			colorTheme: () => LocalizedString
			logOut: {
				/**
				 * We were not able to sign you out
				 */
				errorMessage: () => LocalizedString
			}
		}
	}
	common: {
		/**
		 * nebo
		 */
		or: () => LocalizedString
		/**
		 * a
		 */
		and: () => LocalizedString
		/**
		 * další
		 */
		'continue': () => LocalizedString
		/**
		 * zpět
		 */
		back: () => LocalizedString
		/**
		 * ano
		 */
		yes: () => LocalizedString
		/**
		 * ne
		 */
		no: () => LocalizedString
		/**
		 * uložit
		 */
		save: () => LocalizedString
		/**
		 * nastavení
		 */
		settings: () => LocalizedString
	}
	component: {
		CookiesAlert: {
			/**
			 * Tato stránka používá soubory cookie k ukládání relací uživatelů a dat uživatelů..
			 */
			title: () => LocalizedString
			/**
			 * Přijmout soubory cookie
			 */
			acceptButtonLabel: () => LocalizedString
		}
		SystemDownAlert: {
			/**
			 * Omlouváme se, naše systémy jsou dočasně nedostupné
			 */
			title: () => LocalizedString
			/**
			 * Pracujeme na tom
			 */
			message: () => LocalizedString
			/**
			 * Můžete nás podpořit darem, abychom mohli koupit lepší server
			 */
			donationAsking: () => LocalizedString
		}
		GPSOffAlert: {
			/**
			 * Vaše GPS není zaplá
			 */
			title: () => LocalizedString
			/**
			 * Vaše GPS není zaplá nebo jste neudělil povolení, prohlížeči chrom nebo safari, o používání GPS. Jestli jste geolokaci povolili a stále to nefunguje, zkuste se pohnout.
			 */
			message: () => LocalizedString
		}
		NoPetFound: {
			/**
			 * No pets found
			 */
			title: () => LocalizedString
			/**
			 * Go ahead and create a page for your pet!
			 */
			message: () => LocalizedString
		}
		CreateNewPetModal: {
			/**
			 * create new pet
			 */
			title: () => LocalizedString
			/**
			 * save
			 */
			saveButtonLabel: () => LocalizedString
		}
		UpdatePetModal: {
			/**
			 * update your pet
			 */
			title: () => LocalizedString
			/**
			 * update
			 */
			saveButtonLabel: () => LocalizedString
		}
		PetNameInput: {
			/**
			 * your pets name
			 */
			title: () => LocalizedString
		}
		PetAddressInput: {
			/**
			 * your pets address
			 */
			title: () => LocalizedString
			/**
			 * find your pet accurate location using the map
			 */
			mapTitle: () => LocalizedString
		}
		PetAllergensInput: {
			/**
			 * Allergens
			 */
			title: () => LocalizedString
		}
		OwnerPhoneNumberInput: {
			/**
			 * Your phone number
			 */
			title: () => LocalizedString
		}
		PetTreatInput: {
			/**
			 * How to treat your pet?
			 */
			title: () => LocalizedString
		}
		PetCustomTextInput: {
			placeholder: {
				/**
				 * title
				 */
				title: () => LocalizedString
				/**
				 * text
				 */
				text: () => LocalizedString
			}
		}
		SavingModal: {
			/**
			 * saving...
			 */
			label: () => LocalizedString
		}
		ErrorModal: {
			/**
			 * Error occured
			 */
			title: () => LocalizedString
			/**
			 * Please try it again
			 */
			text: () => LocalizedString
		}
		SavedModal: {
			/**
			 * saved
			 */
			label: () => LocalizedString
			/**
			 * go back
			 */
			returningButtonLabel: () => LocalizedString
		}
		PetAllergensItem: {
			/**
			 * Pet's allergens
			 */
			title: () => LocalizedString
		}
		PetTreatItem: {
			/**
			 * How to treat me?
			 */
			title: () => LocalizedString
		}
		PetPictureInput: {
			/**
			 * Pet's picture
			 */
			title: () => LocalizedString
		}
		RequiredBadge: {
			/**
			 * required
			 */
			label: () => LocalizedString
		}
		RequiredFieldsEmptlyPetCreatingErrorModal: {
			/**
			 * Required fields are empty
			 */
			title: () => LocalizedString
			/**
			 * Please fill up all required fields
			 */
			text: () => LocalizedString
		}
		PetUrlItem: {
			/**
			 * pet's url
			 */
			label: () => LocalizedString
			/**
			 * copied!
			 */
			copied: () => LocalizedString
		}
		EditPetButton: {
			/**
			 * Edit pet
			 */
			label: () => LocalizedString
		}
		DeletePetButton: {
			/**
			 * Delete pet
			 */
			label: () => LocalizedString
			modal: {
				/**
				 * Delete your pet
				 */
				title: () => LocalizedString
				/**
				 * If you delete your pet, you will not be able to recover it. Are you sure you want to do this?
				 */
				text: () => LocalizedString
			}
		}
		DeletingModal: {
			/**
			 * deleting....
			 */
			label: () => LocalizedString
		}
		DeletedModal: {
			/**
			 * deleted
			 */
			label: () => LocalizedString
			/**
			 * go back
			 */
			returningButtonLabel: () => LocalizedString
		}
		LanguageSwitch: {
			/**
			 * english
			 */
			english: () => LocalizedString
			/**
			 * czech
			 */
			czech: () => LocalizedString
		}
		LogOutButton: {
			/**
			 * Log out
			 */
			label: () => LocalizedString
		}
		ButtonLinkToDeveloperPage: {
			/**
			 * Vývojář and majitel
			 */
			label: () => LocalizedString
		}
		PetAddressItem: {
			/**
			 * I live here
			 */
			title: () => LocalizedString
			/**
			 * See on map
			 */
			seeOnMap: () => LocalizedString
		}
	}
	error: {
		/**
		 * Došlo k neočekávané chybě, prosím, sdílejte to s týmem podpory
		 */
		unexpectedError: () => LocalizedString
	}
}

export type Formatters = {}
