// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'cs'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	page: {
		signIn: {
			/**
			 * P​ř​i​h​l​á​š​e​n​í​ ​n​e​b​y​l​o​ ​ú​s​p​ě​š​n​é
			 */
			unsuccessfulLogin: string
			/**
			 * V​í​t​e​j​t​e​ ​d​o​ ​a​p​l​i​k​a​c​e​ ​M​y​ ​p​e​t​!​ ​
		​ ​C​h​c​e​t​e​ ​m​í​t​ ​j​i​s​t​o​t​u​,​ ​ž​e​ ​o​ ​v​a​š​e​h​o​ ​m​a​z​l​í​č​k​a​ ​b​u​d​e​ ​d​o​b​ř​e​ ​p​o​s​t​a​r​á​n​o​,​ ​p​o​k​u​d​ ​s​e​ ​z​a​t​o​u​l​á​?​ ​
		​ ​R​e​g​i​s​t​r​u​j​t​e​ ​s​e​ ​d​o​ ​a​p​l​i​k​a​c​e​ ​a​ ​v​y​t​v​o​ř​t​e​ ​s​i​ ​p​s​í​ ​z​n​á​m​k​u​!
			 */
			welcome: string
		}
		oauth: {
			success: {
				/**
				 * W​e​ ​a​r​e​ ​s​o​r​r​y​,​ ​w​e​ ​w​e​r​e​ ​n​o​t​ ​a​b​l​e​ ​t​o​ ​s​i​g​n​ ​y​o​u​ ​i​n​ ​t​h​e​ ​M​y​ ​P​e​t​s​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​i​t​ ​a​g​a​i​n​.
				 */
				errorMessage: string
			}
		}
		settings: {
			/**
			 * L​a​n​g​u​a​g​e
			 */
			language: string
			/**
			 * C​o​l​o​r​ ​t​h​e​m​e
			 */
			colorTheme: string
			logOut: {
				/**
				 * W​e​ ​w​e​r​e​ ​n​o​t​ ​a​b​l​e​ ​t​o​ ​s​i​g​n​ ​y​o​u​ ​o​u​t
				 */
				errorMessage: string
			}
		}
		selling: {
			/**
			 * T​h​i​s​ ​t​a​g​ ​f​e​a​t​u​r​e​s​ ​b​o​t​h​ ​a​ ​Q​R​ ​c​o​d​e​ ​a​n​d​ ​N​F​C​ ​t​e​c​h​n​o​l​o​g​y​ ​t​o​ ​m​a​k​e​ ​i​t​ ​e​a​s​y​ ​f​o​r​ ​a​n​y​o​n​e​ ​w​h​o​ ​f​i​n​d​s​ ​y​o​u​r​ ​p​e​t​ ​t​o​ ​a​c​c​e​s​s​ ​i​m​p​o​r​t​a​n​t​ ​i​n​f​o​r​m​a​t​i​o​n​.​ ​B​y​ ​s​i​m​p​l​y​ ​s​c​a​n​n​i​n​g​ ​t​h​e​ ​Q​R​ ​c​o​d​e​ ​w​i​t​h​ ​t​h​e​i​r​ ​p​h​o​n​e​ ​o​r​ ​p​l​a​c​i​n​g​ ​a​n​ ​N​F​C​-​e​n​a​b​l​e​d​ ​d​e​v​i​c​e​ ​n​e​a​r​ ​t​h​e​ ​t​a​g​,​ ​t​h​e​y​ ​c​a​n​ ​r​e​t​r​i​e​v​e​ ​y​o​u​r​ ​p​e​t​'​s​ ​d​e​t​a​i​l​s​ ​a​n​d​ ​e​v​e​n​ ​s​e​n​d​ ​y​o​u​ ​i​t​s​ ​l​o​c​a​t​i​o​n​.​ ​T​h​e​ ​Q​R​ ​c​o​d​e​ ​a​l​l​o​w​s​ ​f​o​r​ ​q​u​i​c​k​ ​a​c​c​e​s​s​ ​b​y​ ​t​a​k​i​n​g​ ​a​ ​p​h​o​t​o​,​ ​w​h​i​l​e​ ​t​h​e​ ​N​F​C​ ​f​u​n​c​t​i​o​n​a​l​i​t​y​ ​p​r​o​v​i​d​e​s​ ​i​n​s​t​a​n​t​ ​i​n​f​o​r​m​a​t​i​o​n​ ​w​i​t​h​ ​a​ ​t​a​p​.
			 */
			sellingTagNFC: string
			/**
			 * T​h​i​s​ ​t​a​g​ ​f​e​a​t​u​r​e​s​ ​a​ ​Q​R​ ​c​o​d​e​,​ ​m​a​k​i​n​g​ ​i​t​ ​e​a​s​y​ ​f​o​r​ ​a​n​y​o​n​e​ ​w​h​o​ ​f​i​n​d​s​ ​y​o​u​r​ ​p​e​t​ ​t​o​ ​a​c​c​e​s​s​ ​i​m​p​o​r​t​a​n​t​ ​i​n​f​o​r​m​a​t​i​o​n​.​ ​B​y​ ​s​i​m​p​l​y​ ​s​c​a​n​n​i​n​g​ ​t​h​e​ ​Q​R​ ​c​o​d​e​ ​w​i​t​h​ ​t​h​e​i​r​ ​p​h​o​n​e​,​ ​t​h​e​y​ ​c​a​n​ ​r​e​t​r​i​e​v​e​ ​y​o​u​r​ ​p​e​t​'​s​ ​d​e​t​a​i​l​s​ ​a​n​d​ ​e​v​e​n​ ​s​e​n​d​ ​y​o​u​ ​i​t​s​ ​l​o​c​a​t​i​o​n​.​ ​T​h​e​ ​Q​R​ ​c​o​d​e​ ​a​l​l​o​w​s​ ​f​o​r​ ​q​u​i​c​k​ ​a​c​c​e​s​s​ ​b​y​ ​t​a​k​i​n​g​ ​a​ ​p​h​o​t​o​.
			 */
			sellingTagQR: string
		}
	}
	common: {
		/**
		 * n​e​b​o
		 */
		or: string
		/**
		 * a
		 */
		and: string
		/**
		 * d​a​l​š​í
		 */
		'continue': string
		/**
		 * z​p​ě​t
		 */
		back: string
		/**
		 * a​n​o
		 */
		yes: string
		/**
		 * n​e
		 */
		no: string
		/**
		 * u​l​o​ž​i​t
		 */
		save: string
		/**
		 * n​a​s​t​a​v​e​n​í
		 */
		settings: string
	}
	component: {
		CookiesAlert: {
			/**
			 * T​a​t​o​ ​s​t​r​á​n​k​a​ ​p​o​u​ž​í​v​á​ ​s​o​u​b​o​r​y​ ​c​o​o​k​i​e​ ​k​ ​u​k​l​á​d​á​n​í​ ​r​e​l​a​c​í​ ​u​ž​i​v​a​t​e​l​ů​ ​a​ ​d​a​t​ ​u​ž​i​v​a​t​e​l​ů​.​.
			 */
			title: string
			/**
			 * P​ř​i​j​m​o​u​t​ ​s​o​u​b​o​r​y​ ​c​o​o​k​i​e
			 */
			acceptButtonLabel: string
		}
		SystemDownAlert: {
			/**
			 * O​m​l​o​u​v​á​m​e​ ​s​e​,​ ​n​a​š​e​ ​s​y​s​t​é​m​y​ ​j​s​o​u​ ​d​o​č​a​s​n​ě​ ​n​e​d​o​s​t​u​p​n​é
			 */
			title: string
			/**
			 * P​r​a​c​u​j​e​m​e​ ​n​a​ ​t​o​m
			 */
			message: string
			/**
			 * M​ů​ž​e​t​e​ ​n​á​s​ ​p​o​d​p​o​ř​i​t​ ​d​a​r​e​m​,​ ​a​b​y​c​h​o​m​ ​m​o​h​l​i​ ​k​o​u​p​i​t​ ​l​e​p​š​í​ ​s​e​r​v​e​r
			 */
			donationAsking: string
		}
		GPSOffAlert: {
			/**
			 * V​a​š​e​ ​G​P​S​ ​n​e​n​í​ ​z​a​p​l​á
			 */
			title: string
			/**
			 * V​a​š​e​ ​G​P​S​ ​n​e​n​í​ ​z​a​p​l​á​ ​n​e​b​o​ ​j​s​t​e​ ​n​e​u​d​ě​l​i​l​ ​p​o​v​o​l​e​n​í​,​ ​p​r​o​h​l​í​ž​e​č​i​ ​c​h​r​o​m​ ​n​e​b​o​ ​s​a​f​a​r​i​,​ ​o​ ​p​o​u​ž​í​v​á​n​í​ ​G​P​S​.​ ​J​e​s​t​l​i​ ​j​s​t​e​ ​g​e​o​l​o​k​a​c​i​ ​p​o​v​o​l​i​l​i​ ​a​ ​s​t​á​l​e​ ​t​o​ ​n​e​f​u​n​g​u​j​e​,​ ​z​k​u​s​t​e​ ​s​e​ ​p​o​h​n​o​u​t​.
			 */
			message: string
		}
		NoPetFound: {
			/**
			 * N​o​ ​p​e​t​s​ ​f​o​u​n​d
			 */
			title: string
			/**
			 * G​o​ ​a​h​e​a​d​ ​a​n​d​ ​c​r​e​a​t​e​ ​a​ ​p​a​g​e​ ​f​o​r​ ​y​o​u​r​ ​p​e​t​!
			 */
			message: string
		}
		CreateNewPetModal: {
			/**
			 * c​r​e​a​t​e​ ​n​e​w​ ​p​e​t
			 */
			title: string
			/**
			 * s​a​v​e
			 */
			saveButtonLabel: string
		}
		UpdatePetModal: {
			/**
			 * u​p​d​a​t​e​ ​y​o​u​r​ ​p​e​t
			 */
			title: string
			/**
			 * u​p​d​a​t​e
			 */
			saveButtonLabel: string
		}
		PetNameInput: {
			/**
			 * y​o​u​r​ ​p​e​t​s​ ​n​a​m​e
			 */
			title: string
		}
		PetAddressInput: {
			/**
			 * y​o​u​r​ ​p​e​t​s​ ​a​d​d​r​e​s​s
			 */
			title: string
			/**
			 * f​i​n​d​ ​y​o​u​r​ ​p​e​t​ ​a​c​c​u​r​a​t​e​ ​l​o​c​a​t​i​o​n​ ​u​s​i​n​g​ ​t​h​e​ ​m​a​p
			 */
			mapTitle: string
		}
		PetAllergensInput: {
			/**
			 * A​l​l​e​r​g​e​n​s
			 */
			title: string
		}
		OwnerPhoneNumberInput: {
			/**
			 * Y​o​u​r​ ​p​h​o​n​e​ ​n​u​m​b​e​r
			 */
			title: string
		}
		PetTreatInput: {
			/**
			 * H​o​w​ ​t​o​ ​t​r​e​a​t​ ​y​o​u​r​ ​p​e​t​?
			 */
			title: string
		}
		PetCustomTextInput: {
			/**
			 * C​u​s​t​o​m​ ​f​i​e​l​d​s
			 */
			title: string
			placeholder: {
				/**
				 * t​i​t​l​e
				 */
				title: string
				/**
				 * t​e​x​t
				 */
				text: string
			}
		}
		SavingModal: {
			/**
			 * s​a​v​i​n​g​.​.​.
			 */
			label: string
		}
		ErrorModal: {
			/**
			 * E​r​r​o​r​ ​o​c​c​u​r​e​d
			 */
			title: string
		}
		SavedModal: {
			/**
			 * s​a​v​e​d
			 */
			label: string
			/**
			 * g​o​ ​b​a​c​k
			 */
			returningButtonLabel: string
		}
		PetAllergensItem: {
			/**
			 * P​e​t​'​s​ ​a​l​l​e​r​g​e​n​s
			 */
			title: string
		}
		PetTreatItem: {
			/**
			 * H​o​w​ ​t​o​ ​t​r​e​a​t​ ​m​e​?
			 */
			title: string
		}
		PetPictureInput: {
			/**
			 * P​e​t​'​s​ ​p​i​c​t​u​r​e
			 */
			title: string
		}
		RequiredBadge: {
			/**
			 * r​e​q​u​i​r​e​d
			 */
			label: string
		}
		RequiredFieldsEmptlyPetCreatingErrorModal: {
			/**
			 * R​e​q​u​i​r​e​d​ ​f​i​e​l​d​s​ ​a​r​e​ ​e​m​p​t​y
			 */
			title: string
			/**
			 * P​l​e​a​s​e​ ​f​i​l​l​ ​u​p​ ​a​l​l​ ​r​e​q​u​i​r​e​d​ ​f​i​e​l​d​s
			 */
			text: string
		}
		PetUrlItem: {
			/**
			 * p​e​t​'​s​ ​u​r​l
			 */
			label: string
			/**
			 * c​o​p​i​e​d​!
			 */
			copied: string
		}
		EditPetButton: {
			/**
			 * E​d​i​t​ ​p​e​t
			 */
			label: string
		}
		DeletePetButton: {
			/**
			 * D​e​l​e​t​e​ ​p​e​t
			 */
			label: string
			modal: {
				/**
				 * D​e​l​e​t​e​ ​y​o​u​r​ ​p​e​t
				 */
				title: string
				/**
				 * I​f​ ​y​o​u​ ​d​e​l​e​t​e​ ​y​o​u​r​ ​p​e​t​,​ ​y​o​u​ ​w​i​l​l​ ​n​o​t​ ​b​e​ ​a​b​l​e​ ​t​o​ ​r​e​c​o​v​e​r​ ​i​t​.​ ​A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​o​ ​t​h​i​s​?
				 */
				text: string
			}
		}
		DeletingModal: {
			/**
			 * d​e​l​e​t​i​n​g​.​.​.​.
			 */
			label: string
		}
		DeletedModal: {
			/**
			 * d​e​l​e​t​e​d
			 */
			label: string
			/**
			 * g​o​ ​b​a​c​k
			 */
			returningButtonLabel: string
		}
		LanguageSwitch: {
			/**
			 * e​n​g​l​i​s​h
			 */
			english: string
			/**
			 * c​z​e​c​h
			 */
			czech: string
		}
		LogOutButton: {
			/**
			 * L​o​g​ ​o​u​t
			 */
			label: string
		}
		ButtonLinkToDeveloperPage: {
			/**
			 * V​ý​v​o​j​á​ř​ ​a​n​d​ ​m​a​j​i​t​e​l
			 */
			label: string
		}
		PetAddressItem: {
			/**
			 * I​ ​l​i​v​e​ ​h​e​r​e
			 */
			title: string
		}
		FoundPetButton: {
			/**
			 * I​ ​f​o​u​n​d​ ​t​h​i​s​ ​p​e​t​!
			 */
			label: string
			Modal: {
				/**
				 * I​ ​f​o​u​n​d​ ​t​h​i​s​ ​p​e​t
				 */
				title: string
				/**
				 * Y​o​u​ ​c​a​n​ ​s​e​n​d​ ​y​o​u​r​ ​c​u​r​r​e​n​t​ ​l​o​c​a​t​i​o​n​ ​t​o​ ​t​h​e​ ​o​w​n​e​r​ ​o​f​ ​t​h​e​ ​d​o​g​.
				 */
				text: string
				/**
				 * S​e​n​d​ ​m​y​ ​c​u​r​r​e​n​t​ ​l​o​c​a​t​i​o​n
				 */
				buttonLabel: string
				/**
				 * Y​o​u​r​ ​c​u​r​r​e​n​t​ ​l​o​c​a​t​i​o​n​ ​h​a​s​ ​b​e​e​n​ ​s​e​n​t
				 */
				sent: string
			}
		}
		SeeOnGoogleMapsButton: {
			/**
			 * S​e​e​ ​o​n​ ​G​o​o​g​l​e​ ​m​a​p
			 */
			label: string
		}
		PetFoundLocationItem: {
			/**
			 * Y​o​u​r​ ​p​e​t​ ​w​a​s​ ​f​o​u​n​d​,​ ​c​l​i​c​k​ ​a​n​d​ ​f​o​u​n​d​ ​o​u​t​ ​w​h​e​r​e
			 */
			buttonLabel: string
			modal: {
				/**
				 * L​o​c​a​t​i​o​n​s​ ​w​h​e​r​e​ ​y​o​u​r​ ​p​e​t​ ​w​a​s​ ​f​o​u​n​d
				 */
				title: string
			}
		}
		NoContent: {
			/**
			 * N​o​t​h​i​n​g​ ​h​e​r​e
			 */
			nothingHere: string
		}
		LoadingModal: {
			/**
			 * l​o​a​d​i​n​g​.​.​.
			 */
			label: string
		}
		DeleteButton: {
			/**
			 * D​e​l​e​t​e
			 */
			label: string
		}
		Terms: {
			/**
			 * C​o​n​d​i​t​i​o​n​s​ ​f​o​r​ ​a​p​p​l​i​c​a​t​i​o​n​ ​u​s​i​n​g
			 */
			terms: string
			/**
			 * A​c​c​e​p​t
			 */
			acceptButtonLabel: string
		}
		SeeOnMapButton: {
			/**
			 * S​e​e​ ​o​n​ ​m​a​p
			 */
			label: string
		}
		SellingCard: {
			/**
			 * s​i​z​e​s
			 */
			sizes: string
		}
		PetAgeInput: {
			datePicker: {
				/**
				 * D​a​t​e​ ​o​f​ ​b​i​r​t​h​d​a​y
				 */
				label: string
			}
		}
		PetAgeItem: {
			/**
			 * y​e​a​r​s​ ​o​l​d
			 */
			yearsOld: string
			/**
			 * b​o​r​n
			 */
			born: string
		}
		PetWeightInput: {
			/**
			 * P​e​t​'​s​ ​w​e​i​g​h​t
			 */
			title: string
			/**
			 * A​d​d​ ​w​e​i​g​h​t
			 */
			buttonAddWeight: string
			/**
			 * R​e​m​o​v​e​ ​w​e​i​g​h​t
			 */
			buttonRemoveWeight: string
		}
		PetWeightItem: {
			/**
			 * M​y​ ​w​e​i​g​h​t​ ​i​s
			 */
			title: string
		}
		DoneModal: {
			/**
			 * G​o​ ​b​a​c​k
			 */
			returningButtonLabel: string
			/**
			 * D​o​n​e
			 */
			label: string
		}
		UpdatePetIdTranslation: {
			/**
			 * U​p​d​a​t​e​ ​p​e​t​'​s​ ​t​a​g
			 */
			buttonLabel: string
			modal: {
				/**
				 * U​p​d​a​t​e​ ​y​o​u​r​ ​p​e​t​'​s
				 */
				title: string
				/**
				 * P​u​t​ ​y​o​u​r​ ​c​o​d​e​.
				 */
				text: string
				/**
				 * U​p​d​a​t​e​ ​t​a​g
				 */
				updateTagButtonLabel: string
			}
			/**
			 * O​p​p​p​s​,​ ​s​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​,​ ​i​f​ ​y​o​u​ ​t​h​i​n​k​ ​t​h​a​t​ ​y​o​u​ ​w​r​o​t​e​ ​a​ ​r​i​g​h​t​ ​c​o​d​e​ ​a​n​d​ ​y​o​u​ ​d​o​n​t​ ​h​a​v​e​ ​a​n​y​ ​o​t​h​e​r​ ​p​e​t​ ​r​e​g​i​s​t​e​r​e​d​ ​w​i​t​h​ ​t​h​i​s​ ​c​o​d​e​,​ ​p​l​e​a​s​e​ ​c​o​n​t​a​c​t​ ​u​s​.
			 */
			error: string
		}
		SignUpViaPhone: {
			/**
			 * S​i​g​n​ ​u​p​ ​w​i​t​h​ ​p​h​o​n​e​ ​n​u​m​b​e​r
			 */
			buttonLabel: string
			phoneModal: {
				/**
				 * W​r​i​t​e​ ​y​o​u​r​ ​p​h​o​n​e​ ​n​u​m​b​e​r​,​ ​w​e​ ​w​i​l​l​ ​s​e​n​d​ ​y​o​u​ ​a​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e​.
				 */
				title: string
				/**
				 * S​e​n​d
				 */
				sendButtonLabel: string
			}
			verificationModal: {
				/**
				 * W​e​ ​s​e​n​t​ ​y​o​u​ ​a​ ​v​e​r​i​f​i​c​a​t​i​o​n​ ​c​o​d​e​,​ ​w​r​i​t​e​ ​i​t​ ​d​o​w​n​ ​t​o​ ​v​e​r​i​f​y​ ​y​o​u​r​ ​p​h​o​n​e​ ​n​u​m​b​e​r​.
				 */
				title: string
				/**
				 * V​e​r​i​f​y
				 */
				verfifyButtonLabel: string
			}
			/**
			 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​,​ ​c​h​e​c​k​ ​y​o​u​r​ ​n​u​m​b​e​r​ ​t​w​i​c​e​.
			 */
			tokenErrorMessage: string
			/**
			 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​ ​w​i​t​h​ ​t​h​e​ ​v​e​r​i​f​i​c​a​t​i​o​n​,​ ​c​h​e​c​k​ ​y​o​u​r​ ​t​o​k​e​n​ ​t​w​i​c​e​.
			 */
			verificationErrorMessage: string
		}
		PetNotFound: {
			/**
			 * P​e​t​ ​y​o​u​ ​a​r​e​ ​l​o​o​k​i​n​g​ ​f​o​r​ ​w​a​s​ ​n​o​t​ ​f​o​u​n​d​ ​i​n​ ​o​u​r​ ​d​a​t​a​b​a​s​e​.
			 */
			title: string
			/**
			 * I​f​ ​t​h​i​s​ ​i​s​ ​y​o​u​r​ ​t​a​g​,​ ​y​o​u​ ​h​a​v​e​ ​t​o​ ​r​e​g​i​s​t​e​r​ ​i​t​ ​f​i​r​s​t​.​ ​Y​o​u​ ​c​a​n​ ​d​o​ ​t​h​i​s​ ​i​n​ ​y​o​u​r​ ​p​e​t​ ​p​r​o​f​i​l​e​.
			 */
			message: string
		}
		PetSettings: {
			modal: {
				/**
				 * Y​o​u​r​ ​p​e​t​'​s​ ​s​e​t​t​i​n​g​s
				 */
				title: string
			}
			/**
			 * S​e​t​t​i​n​g​s
			 */
			buttonLabel: string
		}
		RemovePetTag: {
			/**
			 * R​e​m​o​v​e​ ​a​ ​p​e​t​ ​t​a​g​ ​o​f​ ​t​h​i​s​ ​p​e​t
			 */
			buttonLabel: string
			modal: {
				/**
				 * R​e​m​o​v​e​ ​a​ ​p​e​t​ ​t​a​g​ ​o​f​ ​t​h​i​s​ ​p​e​t
				 */
				title: string
				/**
				 * A​f​t​e​r​ ​r​e​m​o​v​i​n​g​ ​y​o​u​ ​w​i​l​l​ ​b​e​ ​a​b​l​e​ ​t​o​ ​r​e​g​i​s​t​e​r​ ​t​h​e​ ​t​a​g​ ​b​a​c​k​ ​t​o​ ​t​h​i​s​ ​p​e​t​,​ ​b​u​t​ ​y​o​u​ ​w​i​l​l​ ​a​l​s​o​ ​b​e​ ​a​b​l​e​ ​t​o​ ​r​e​g​i​s​t​e​r​ ​t​h​i​s​ ​t​a​g​ ​t​o​ ​a​ ​d​i​f​f​e​r​e​n​t​ ​p​e​t​ ​o​f​ ​y​o​u​r​s​.
				 */
				text: string
			}
		}
	}
	error: {
		/**
		 * T​h​e​r​e​ ​w​a​s​ ​a​n​ ​u​n​e​x​p​e​c​t​e​d​ ​e​r​r​o​r​,​ ​p​l​e​a​s​e​ ​s​h​a​r​e​ ​t​h​i​s​ ​w​i​t​h​ ​t​h​e​ ​t​e​a​m​ ​o​f​ ​h​e​l​p​.
		 */
		unexpectedError: string
		/**
		 * Y​o​u​r​ ​G​P​S​ ​i​s​ ​o​f​f​,​ ​p​l​e​a​s​e​ ​t​u​r​n​ ​y​o​u​r​ ​G​P​S​ ​o​n​,​ ​t​h​a​t​ ​w​e​ ​c​o​u​l​d​ ​d​e​t​e​r​m​i​n​a​t​e​ ​w​h​e​r​e​ ​y​o​u​ ​a​r​e​.​ ​M​a​y​b​e​ ​y​o​u​ ​j​u​s​t​ ​d​i​d​ ​n​o​t​ ​g​r​a​n​t​e​d​ ​t​h​e​ ​G​P​S​ ​f​o​r​ ​G​o​o​g​l​e​/​S​a​f​a​r​i​ ​o​f​ ​o​u​r​ ​a​p​p​l​i​c​a​t​i​o​n​ ​M​y​p​e​t​s​,​ ​p​l​e​a​s​e​ ​d​o​ ​i​t​ ​a​n​d​ ​t​h​e​n​ ​t​r​y​ ​i​t​ ​a​g​a​i​n​.
		 */
		gpsIsOff: string
	}
}

export type TranslationFunctions = {
	page: {
		signIn: {
			/**
			 * Přihlášení nebylo úspěšné
			 */
			unsuccessfulLogin: () => LocalizedString
			/**
			 * Vítejte do aplikace My pet! 
		 Chcete mít jistotu, že o vašeho mazlíčka bude dobře postaráno, pokud se zatoulá? 
		 Registrujte se do aplikace a vytvořte si psí známku!
			 */
			welcome: () => LocalizedString
		}
		oauth: {
			success: {
				/**
				 * We are sorry, we were not able to sign you in the My Pets. Please try it again.
				 */
				errorMessage: () => LocalizedString
			}
		}
		settings: {
			/**
			 * Language
			 */
			language: () => LocalizedString
			/**
			 * Color theme
			 */
			colorTheme: () => LocalizedString
			logOut: {
				/**
				 * We were not able to sign you out
				 */
				errorMessage: () => LocalizedString
			}
		}
		selling: {
			/**
			 * This tag features both a QR code and NFC technology to make it easy for anyone who finds your pet to access important information. By simply scanning the QR code with their phone or placing an NFC-enabled device near the tag, they can retrieve your pet's details and even send you its location. The QR code allows for quick access by taking a photo, while the NFC functionality provides instant information with a tap.
			 */
			sellingTagNFC: () => LocalizedString
			/**
			 * This tag features a QR code, making it easy for anyone who finds your pet to access important information. By simply scanning the QR code with their phone, they can retrieve your pet's details and even send you its location. The QR code allows for quick access by taking a photo.
			 */
			sellingTagQR: () => LocalizedString
		}
	}
	common: {
		/**
		 * nebo
		 */
		or: () => LocalizedString
		/**
		 * a
		 */
		and: () => LocalizedString
		/**
		 * další
		 */
		'continue': () => LocalizedString
		/**
		 * zpět
		 */
		back: () => LocalizedString
		/**
		 * ano
		 */
		yes: () => LocalizedString
		/**
		 * ne
		 */
		no: () => LocalizedString
		/**
		 * uložit
		 */
		save: () => LocalizedString
		/**
		 * nastavení
		 */
		settings: () => LocalizedString
	}
	component: {
		CookiesAlert: {
			/**
			 * Tato stránka používá soubory cookie k ukládání relací uživatelů a dat uživatelů..
			 */
			title: () => LocalizedString
			/**
			 * Přijmout soubory cookie
			 */
			acceptButtonLabel: () => LocalizedString
		}
		SystemDownAlert: {
			/**
			 * Omlouváme se, naše systémy jsou dočasně nedostupné
			 */
			title: () => LocalizedString
			/**
			 * Pracujeme na tom
			 */
			message: () => LocalizedString
			/**
			 * Můžete nás podpořit darem, abychom mohli koupit lepší server
			 */
			donationAsking: () => LocalizedString
		}
		GPSOffAlert: {
			/**
			 * Vaše GPS není zaplá
			 */
			title: () => LocalizedString
			/**
			 * Vaše GPS není zaplá nebo jste neudělil povolení, prohlížeči chrom nebo safari, o používání GPS. Jestli jste geolokaci povolili a stále to nefunguje, zkuste se pohnout.
			 */
			message: () => LocalizedString
		}
		NoPetFound: {
			/**
			 * No pets found
			 */
			title: () => LocalizedString
			/**
			 * Go ahead and create a page for your pet!
			 */
			message: () => LocalizedString
		}
		CreateNewPetModal: {
			/**
			 * create new pet
			 */
			title: () => LocalizedString
			/**
			 * save
			 */
			saveButtonLabel: () => LocalizedString
		}
		UpdatePetModal: {
			/**
			 * update your pet
			 */
			title: () => LocalizedString
			/**
			 * update
			 */
			saveButtonLabel: () => LocalizedString
		}
		PetNameInput: {
			/**
			 * your pets name
			 */
			title: () => LocalizedString
		}
		PetAddressInput: {
			/**
			 * your pets address
			 */
			title: () => LocalizedString
			/**
			 * find your pet accurate location using the map
			 */
			mapTitle: () => LocalizedString
		}
		PetAllergensInput: {
			/**
			 * Allergens
			 */
			title: () => LocalizedString
		}
		OwnerPhoneNumberInput: {
			/**
			 * Your phone number
			 */
			title: () => LocalizedString
		}
		PetTreatInput: {
			/**
			 * How to treat your pet?
			 */
			title: () => LocalizedString
		}
		PetCustomTextInput: {
			/**
			 * Custom fields
			 */
			title: () => LocalizedString
			placeholder: {
				/**
				 * title
				 */
				title: () => LocalizedString
				/**
				 * text
				 */
				text: () => LocalizedString
			}
		}
		SavingModal: {
			/**
			 * saving...
			 */
			label: () => LocalizedString
		}
		ErrorModal: {
			/**
			 * Error occured
			 */
			title: () => LocalizedString
		}
		SavedModal: {
			/**
			 * saved
			 */
			label: () => LocalizedString
			/**
			 * go back
			 */
			returningButtonLabel: () => LocalizedString
		}
		PetAllergensItem: {
			/**
			 * Pet's allergens
			 */
			title: () => LocalizedString
		}
		PetTreatItem: {
			/**
			 * How to treat me?
			 */
			title: () => LocalizedString
		}
		PetPictureInput: {
			/**
			 * Pet's picture
			 */
			title: () => LocalizedString
		}
		RequiredBadge: {
			/**
			 * required
			 */
			label: () => LocalizedString
		}
		RequiredFieldsEmptlyPetCreatingErrorModal: {
			/**
			 * Required fields are empty
			 */
			title: () => LocalizedString
			/**
			 * Please fill up all required fields
			 */
			text: () => LocalizedString
		}
		PetUrlItem: {
			/**
			 * pet's url
			 */
			label: () => LocalizedString
			/**
			 * copied!
			 */
			copied: () => LocalizedString
		}
		EditPetButton: {
			/**
			 * Edit pet
			 */
			label: () => LocalizedString
		}
		DeletePetButton: {
			/**
			 * Delete pet
			 */
			label: () => LocalizedString
			modal: {
				/**
				 * Delete your pet
				 */
				title: () => LocalizedString
				/**
				 * If you delete your pet, you will not be able to recover it. Are you sure you want to do this?
				 */
				text: () => LocalizedString
			}
		}
		DeletingModal: {
			/**
			 * deleting....
			 */
			label: () => LocalizedString
		}
		DeletedModal: {
			/**
			 * deleted
			 */
			label: () => LocalizedString
			/**
			 * go back
			 */
			returningButtonLabel: () => LocalizedString
		}
		LanguageSwitch: {
			/**
			 * english
			 */
			english: () => LocalizedString
			/**
			 * czech
			 */
			czech: () => LocalizedString
		}
		LogOutButton: {
			/**
			 * Log out
			 */
			label: () => LocalizedString
		}
		ButtonLinkToDeveloperPage: {
			/**
			 * Vývojář and majitel
			 */
			label: () => LocalizedString
		}
		PetAddressItem: {
			/**
			 * I live here
			 */
			title: () => LocalizedString
		}
		FoundPetButton: {
			/**
			 * I found this pet!
			 */
			label: () => LocalizedString
			Modal: {
				/**
				 * I found this pet
				 */
				title: () => LocalizedString
				/**
				 * You can send your current location to the owner of the dog.
				 */
				text: () => LocalizedString
				/**
				 * Send my current location
				 */
				buttonLabel: () => LocalizedString
				/**
				 * Your current location has been sent
				 */
				sent: () => LocalizedString
			}
		}
		SeeOnGoogleMapsButton: {
			/**
			 * See on Google map
			 */
			label: () => LocalizedString
		}
		PetFoundLocationItem: {
			/**
			 * Your pet was found, click and found out where
			 */
			buttonLabel: () => LocalizedString
			modal: {
				/**
				 * Locations where your pet was found
				 */
				title: () => LocalizedString
			}
		}
		NoContent: {
			/**
			 * Nothing here
			 */
			nothingHere: () => LocalizedString
		}
		LoadingModal: {
			/**
			 * loading...
			 */
			label: () => LocalizedString
		}
		DeleteButton: {
			/**
			 * Delete
			 */
			label: () => LocalizedString
		}
		Terms: {
			/**
			 * Conditions for application using
			 */
			terms: () => LocalizedString
			/**
			 * Accept
			 */
			acceptButtonLabel: () => LocalizedString
		}
		SeeOnMapButton: {
			/**
			 * See on map
			 */
			label: () => LocalizedString
		}
		SellingCard: {
			/**
			 * sizes
			 */
			sizes: () => LocalizedString
		}
		PetAgeInput: {
			datePicker: {
				/**
				 * Date of birthday
				 */
				label: () => LocalizedString
			}
		}
		PetAgeItem: {
			/**
			 * years old
			 */
			yearsOld: () => LocalizedString
			/**
			 * born
			 */
			born: () => LocalizedString
		}
		PetWeightInput: {
			/**
			 * Pet's weight
			 */
			title: () => LocalizedString
			/**
			 * Add weight
			 */
			buttonAddWeight: () => LocalizedString
			/**
			 * Remove weight
			 */
			buttonRemoveWeight: () => LocalizedString
		}
		PetWeightItem: {
			/**
			 * My weight is
			 */
			title: () => LocalizedString
		}
		DoneModal: {
			/**
			 * Go back
			 */
			returningButtonLabel: () => LocalizedString
			/**
			 * Done
			 */
			label: () => LocalizedString
		}
		UpdatePetIdTranslation: {
			/**
			 * Update pet's tag
			 */
			buttonLabel: () => LocalizedString
			modal: {
				/**
				 * Update your pet's
				 */
				title: () => LocalizedString
				/**
				 * Put your code.
				 */
				text: () => LocalizedString
				/**
				 * Update tag
				 */
				updateTagButtonLabel: () => LocalizedString
			}
			/**
			 * Oppps, something went wrong, if you think that you wrote a right code and you dont have any other pet registered with this code, please contact us.
			 */
			error: () => LocalizedString
		}
		SignUpViaPhone: {
			/**
			 * Sign up with phone number
			 */
			buttonLabel: () => LocalizedString
			phoneModal: {
				/**
				 * Write your phone number, we will send you a verification code.
				 */
				title: () => LocalizedString
				/**
				 * Send
				 */
				sendButtonLabel: () => LocalizedString
			}
			verificationModal: {
				/**
				 * We sent you a verification code, write it down to verify your phone number.
				 */
				title: () => LocalizedString
				/**
				 * Verify
				 */
				verfifyButtonLabel: () => LocalizedString
			}
			/**
			 * Something went wrong, check your number twice.
			 */
			tokenErrorMessage: () => LocalizedString
			/**
			 * Something went wrong with the verification, check your token twice.
			 */
			verificationErrorMessage: () => LocalizedString
		}
		PetNotFound: {
			/**
			 * Pet you are looking for was not found in our database.
			 */
			title: () => LocalizedString
			/**
			 * If this is your tag, you have to register it first. You can do this in your pet profile.
			 */
			message: () => LocalizedString
		}
		PetSettings: {
			modal: {
				/**
				 * Your pet's settings
				 */
				title: () => LocalizedString
			}
			/**
			 * Settings
			 */
			buttonLabel: () => LocalizedString
		}
		RemovePetTag: {
			/**
			 * Remove a pet tag of this pet
			 */
			buttonLabel: () => LocalizedString
			modal: {
				/**
				 * Remove a pet tag of this pet
				 */
				title: () => LocalizedString
				/**
				 * After removing you will be able to register the tag back to this pet, but you will also be able to register this tag to a different pet of yours.
				 */
				text: () => LocalizedString
			}
		}
	}
	error: {
		/**
		 * There was an unexpected error, please share this with the team of help.
		 */
		unexpectedError: () => LocalizedString
		/**
		 * Your GPS is off, please turn your GPS on, that we could determinate where you are. Maybe you just did not granted the GPS for Google/Safari of our application Mypets, please do it and then try it again.
		 */
		gpsIsOff: () => LocalizedString
	}
}

export type Formatters = {}
