// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'cs'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	page: {
		signIn: {
			/**
			 * P​ř​i​h​l​á​š​e​n​í​ ​n​e​b​y​l​o​ ​ú​s​p​ě​š​n​é
			 */
			unsuccessfulLogin: string
			/**
			 * V​í​t​e​j​t​e​ ​d​o​ ​a​p​l​i​k​a​c​e​ ​M​y​ ​p​e​t​!​ ​
		​ ​C​h​c​e​t​e​ ​m​í​t​ ​j​i​s​t​o​t​u​,​ ​ž​e​ ​o​ ​v​a​š​e​h​o​ ​m​a​z​l​í​č​k​a​ ​b​u​d​e​ ​d​o​b​ř​e​ ​p​o​s​t​a​r​á​n​o​,​ ​p​o​k​u​d​ ​s​e​ ​z​a​t​o​u​l​á​?​ ​
		​ ​R​e​g​i​s​t​r​u​j​t​e​ ​s​e​ ​d​o​ ​a​p​l​i​k​a​c​e​ ​a​ ​v​y​t​v​o​ř​t​e​ ​s​i​ ​p​s​í​ ​z​n​á​m​k​u​!
			 */
			welcome: string
		}
	}
	common: {
		/**
		 * n​e​b​o
		 */
		or: string
		/**
		 * a
		 */
		and: string
		/**
		 * d​a​l​š​í
		 */
		'continue': string
		/**
		 * z​p​ě​t
		 */
		back: string
		/**
		 * a​n​o
		 */
		yes: string
		/**
		 * n​e
		 */
		no: string
		/**
		 * u​l​o​ž​i​t
		 */
		save: string
		/**
		 * n​a​s​t​a​v​e​n​í
		 */
		settings: string
	}
	component: {
		CookiesAlert: {
			/**
			 * T​a​t​o​ ​s​t​r​á​n​k​a​ ​p​o​u​ž​í​v​á​ ​s​o​u​b​o​r​y​ ​c​o​o​k​i​e​ ​k​ ​u​k​l​á​d​á​n​í​ ​r​e​l​a​c​í​ ​u​ž​i​v​a​t​e​l​ů​ ​a​ ​d​a​t​ ​u​ž​i​v​a​t​e​l​ů​,​ ​v​č​e​t​n​ě​ ​a​k​t​u​á​l​n​í​ ​p​o​l​o​h​y​ ​u​ž​i​v​a​t​e​l​ů​.
			 */
			title: string
			/**
			 * P​ř​i​j​m​o​u​t​ ​s​o​u​b​o​r​y​ ​c​o​o​k​i​e
			 */
			acceptButtonLabel: string
		}
		SystemDownAlert: {
			/**
			 * O​m​l​o​u​v​á​m​e​ ​s​e​,​ ​n​a​š​e​ ​s​y​s​t​é​m​y​ ​j​s​o​u​ ​d​o​č​a​s​n​ě​ ​n​e​d​o​s​t​u​p​n​é
			 */
			title: string
			/**
			 * P​r​a​c​u​j​e​m​e​ ​n​a​ ​t​o​m
			 */
			message: string
			/**
			 * M​ů​ž​e​t​e​ ​n​á​s​ ​p​o​d​p​o​ř​i​t​ ​d​a​r​e​m​,​ ​a​b​y​c​h​o​m​ ​m​o​h​l​i​ ​k​o​u​p​i​t​ ​l​e​p​š​í​ ​s​e​r​v​e​r
			 */
			donationAsking: string
		}
		GPSOffAlert: {
			/**
			 * V​a​š​e​ ​G​P​S​ ​n​e​n​í​ ​z​a​p​l​á
			 */
			title: string
			/**
			 * V​a​š​e​ ​G​P​S​ ​n​e​n​í​ ​z​a​p​l​á​ ​n​e​b​o​ ​j​s​t​e​ ​n​e​u​d​ě​l​i​l​ ​p​o​v​o​l​e​n​í​,​ ​p​r​o​h​l​í​ž​e​č​i​ ​c​h​r​o​m​ ​n​e​b​o​ ​s​a​f​a​r​i​,​ ​o​ ​p​o​u​ž​í​v​á​n​í​ ​G​P​S​.​ ​J​e​s​t​l​i​ ​j​s​t​e​ ​g​e​o​l​o​k​a​c​i​ ​p​o​v​o​l​i​l​i​ ​a​ ​s​t​á​l​e​ ​t​o​ ​n​e​f​u​n​g​u​j​e​,​ ​z​k​u​s​t​e​ ​s​e​ ​p​o​h​n​o​u​t​.
			 */
			message: string
		}
		PetNameInput: {
			/**
			 * E​d​i​t​ ​y​o​u​r​ ​p​e​t​`​s​ ​n​a​m​e
			 */
			title: string
		}
	}
	error: {
		/**
		 * D​o​š​l​o​ ​k​ ​n​e​o​č​e​k​á​v​a​n​é​ ​c​h​y​b​ě​,​ ​p​r​o​s​í​m​,​ ​s​d​í​l​e​j​t​e​ ​t​o​ ​s​ ​t​ý​m​e​m​ ​p​o​d​p​o​r​y
		 */
		unexpectedError: string
	}
}

export type TranslationFunctions = {
	page: {
		signIn: {
			/**
			 * Přihlášení nebylo úspěšné
			 */
			unsuccessfulLogin: () => LocalizedString
			/**
			 * Vítejte do aplikace My pet! 
		 Chcete mít jistotu, že o vašeho mazlíčka bude dobře postaráno, pokud se zatoulá? 
		 Registrujte se do aplikace a vytvořte si psí známku!
			 */
			welcome: () => LocalizedString
		}
	}
	common: {
		/**
		 * nebo
		 */
		or: () => LocalizedString
		/**
		 * a
		 */
		and: () => LocalizedString
		/**
		 * další
		 */
		'continue': () => LocalizedString
		/**
		 * zpět
		 */
		back: () => LocalizedString
		/**
		 * ano
		 */
		yes: () => LocalizedString
		/**
		 * ne
		 */
		no: () => LocalizedString
		/**
		 * uložit
		 */
		save: () => LocalizedString
		/**
		 * nastavení
		 */
		settings: () => LocalizedString
	}
	component: {
		CookiesAlert: {
			/**
			 * Tato stránka používá soubory cookie k ukládání relací uživatelů a dat uživatelů, včetně aktuální polohy uživatelů.
			 */
			title: () => LocalizedString
			/**
			 * Přijmout soubory cookie
			 */
			acceptButtonLabel: () => LocalizedString
		}
		SystemDownAlert: {
			/**
			 * Omlouváme se, naše systémy jsou dočasně nedostupné
			 */
			title: () => LocalizedString
			/**
			 * Pracujeme na tom
			 */
			message: () => LocalizedString
			/**
			 * Můžete nás podpořit darem, abychom mohli koupit lepší server
			 */
			donationAsking: () => LocalizedString
		}
		GPSOffAlert: {
			/**
			 * Vaše GPS není zaplá
			 */
			title: () => LocalizedString
			/**
			 * Vaše GPS není zaplá nebo jste neudělil povolení, prohlížeči chrom nebo safari, o používání GPS. Jestli jste geolokaci povolili a stále to nefunguje, zkuste se pohnout.
			 */
			message: () => LocalizedString
		}
		PetNameInput: {
			/**
			 * Edit your pet`s name
			 */
			title: () => LocalizedString
		}
	}
	error: {
		/**
		 * Došlo k neočekávané chybě, prosím, sdílejte to s týmem podpory
		 */
		unexpectedError: () => LocalizedString
	}
}

export type Formatters = {}
